### ISSUE TITLE
Ubuntu 16.10 - Flowgraph won't execute

### ISSUE THREAD

**Issue by michelinok** [sq5bpf/telive#10]
Hi!
I've made a fresh 16.10 ubuntu installation and used your install script to install telive.
First time i've ran the grc, i got this error:

The xterm executable 'xterm' is missing

then when i start the grc it start and stop immediately (nothing appears).

Any idea?

**Comment by tapiov** [comment]
How about "which xterm", to see if it's really missing? Shouldn't be though.

**Comment by michelinok** [comment]
which xterm:

michele@workstation:~$ which xterm
/usr/bin/xterm

grc.conf:

[grc]
global_blocks_path = /usr/share/gnuradio/grc/blocks:/usr/local/share/gnuradio/grc/blocks
local_blocks_path =
xterm_executable = /usr/bin/xterm
canvas_font_size = 8
canvas_default_size = 1280, 1024

Should i blacklist some modules or do something (just an idea) before running the flowgraph?

**Comment by michelinok** [comment]
ok...reinstalled a 16.04 ubuntu and i can run the flowgraph...the problem is that when i start it, it's size is very small and if i drag the borders the window is blank
