### ISSUE TITLE
E: Unable to locate package gqrx

### ISSUE THREAD

**Issue by Torrio888** [sq5bpf/telive#18]
E: Unable to locate package gqrx
Unknown distro [ubuntu 18.2], please report it, and send the below information:
NAME="Linux Mint"
VERSION="18.2 (Sonya)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 18.2"
VERSION_ID="18.2"
HOME_URL="http://www.linuxmint.com/"
SUPPORT_URL="http://forums.linuxmint.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/linuxmint/"
VERSION_CODENAME=sonya
UBUNTU_CODENAME=xenial

**Comment by Torrio888** [comment]
gqrx is already installed and even if I purge the installation and run the scrtp again I get the same error.

**Comment by sq5bpf** [comment]
this is an old issue, it should be fixed now (but if it isn't, please report it)
