### ISSUE TITLE
Instructions: How to get this running on a RPi3?

### ISSUE THREAD

**Issue by E3V3A** [sq5bpf/telive#19]
I'd like to have this running on a RPi3, but I can't find any working instructions. 
Does anyone have some insight or links how to make this happen? 

@sq5bpf 
You mentioned somewhere you got this working. Could you post some details about what you did? 

There are some old RPi2 instructions [here](http://blog.opentetra.nl/) but they rely on installing ArchLinux on the Pi, which should not be necessary. There are also some scattered bits and pieces [over here](https://forums.radioreference.com/voice-control-channel-decoding-software/302347-tetra-decoding.html).

**Comment by sq5bpf** [comment]
use the install_telive.sh script
