### ISSUE TITLE
Install script fails on ubuntu 18

### ISSUE THREAD

**Issue by asiudoisjdfo** [sq5bpf/telive#23]
Trying to install on ubuntu 18 which has other rtlsdr apps working (grc, gqrx, urh etc). Running the install script yields:

/home/spongebob/anaconda3/lib/./libtinfow.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:13: recipe for target 'telive' failed
make: *** [telive] Error 1

I have noooo clue how to solve this, even after ducking on the internets...  any clues maybe? :-)

**Comment by sq5bpf** [comment]
the install has probably been broken by installing some strange packages in  /home/spongebob/anaconda3

try to add another account (and give it rights to use sudo and to the rtl devices), and install using this account. maybe this will work. if not, then install a clean system
