### ISSUE TITLE
Install failing with this error

### ISSUE THREAD

**Issue by graham30rad** [sq5bpf/telive#24]
W: GPG error: file:/var/cuda-repo-10-1-local-10.1.105-418.39  Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY F60F4B3D********
E: The repository 'file:/var/cuda-repo-10-1-local-10.1.105-418.39  Release' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Repository 'http://security.ubuntu.com/ubuntu bionic-security InRelease' changed its 'Suite' value from 'bionic-updates' to 'bionic-security'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
### ERROR UPDATING PACKAGE LISTS!
Make sure you have full internet access, and that your distribution's package repositories are currently avaliable
Try to run 'sudo apt-get update' by hand, and see what you have to do to resolve it

Ubuntu 18.04.2
Memory = 15.6 GiB
Processor = Intel® Core™ i5-7500 CPU @ 3.40GHz × 4
Graphics = GeForce GTX 1050 Ti/PCIe/SSE2
GNOME = 3.28.2
OS = 64-bit

I ran the script and it spat out this error at the end.
I have tried the suggested sudo apt-get update but no joy.
Any help would be great. tia...

**Comment by sq5bpf** [comment]
this has nothing to do with telive, the package manager is broken because you've added some strange repository to it

please fix your package manager or reinstall the system.
