### ISSUE TITLE
Scanning does not appear to do anything

### ISSUE THREAD

**Issue by adryd325** [sq5bpf/telive#26]
The "scan until the first available network is found" feature does not seem to be working for me. 

Reading the documentation would suggest that it does not change the base-band frequency and only looks within the data telive is being fed. I set TETRA_SCAN_LIST to "412.900-413.000/12.5" and the base-band frequency to 412.9475 (the center of a known good TETRA frequency). When activating the scanner mode, nothing is found after ~10 minutes of letting it run.

It's possible I'm misunderstanding the documentation. If this is the case, please let me know

**Comment by sq5bpf** [comment]
are you using a receiver with xmlrpc?

does the frequency change while scanning? try telive_1ch_simple_gr37_udp_xmlrpc.grc and look at the spectrum while scanning

are you sure you have a tetra downlink on 412.9475 ? in most bandplans this would be the uplink frequency, and the downlink would be 10MHz higher (most installations i've seen use a 10MHz offset), on 422.9475 MHz . your location might be different of course

**Comment by adryd325** [comment]
I'm not exactly sure what I changed, but I reinstalled everything and it began to work. It's likely my fault somehow.

I hate to be the person who makes an issue the closes it with no solution, but I'm not even sure what my solution was.

Thank you for this great piece of software btw!
