### ISSUE TITLE
Export SDS messages to tetra1.kml file

### ISSUE THREAD

**Issue by enrutador** [sq5bpf/telive#27]
Good morning from Spain
Impress yourself with the work you have done. Voice decoding is perfect with hackrf. The problem I am having is in the export of the tetra1.kml file, I cannot get telive to create the file and export that data. I do receive the plot in rxx:

`20200318 11:35:33 FUNC:NETINFO1 CCODE:36 MCC:00d6 MNC:0008 DLF:390337500 ULF:380337500 LA:1029 RX:1 
20200318 11:35:33 FUNC:SDS [0100111101000001001011111111001100110001111000010000010000000101011101010000001000000111001001011100011100100011000001000110001101100011111111100010000000000101000001111110100000011110000000010010000001101111010001000101010000000010101000111001011011101110011000100101011111000001000000001000000100001] 
20200318 11:35:33 FUNC:SDSDEC [CPTI:1 CalledSSI:311131 CallingSSI:311244 CallingEXT:0  UserData4: len:232 protoid:82(Text Messaging) SDS-TL:[ MsgType:SDS-TRANSFER MSG_REF:186 TO_GROUP:1]  coding_scheme:01 DATA:[\x03\x92\xE3\x91\x821\xB1\xFF\x10\x02\x83\xF4\x0F\x00\x907\xA2*\x01Q\xCBw1+\xE0\x80]] RX:1 `

Is it an encrypted message or is it a configuration error?

**Comment by sq5bpf** [comment]
tetra1.kml is a kml file for google earth. sds which contain a known location protocol (LIP and others) will get written there

the sds you have sent is probably some proprietary sds, probably not used for location

**Comment by enrutador** [comment]
Hi a lot of thanks for the clarification
