### ISSUE TITLE
Resume scan after signal lost

### ISSUE THREAD

**Issue by adryd325** [sq5bpf/telive#31]
I'm using telive in a portable scanner setup to listen to the train operators while riding the train. 

I'd like to see a feature which resumes scanning after a signal has been lost for a while. This would help when moving out of coverage of one signal and into another.

I've made an attempt at implementing it in my fork (https://github.com/adryd325/telive/commit/fdb5ac89c84c386ae670c54d8a7dbf123ae4a290); however C is very much out of my comfort zone, and I'd like to see what you could do.

Not relevant to the issue:
I really appreciate this project and its scanning functionality has made my portable listening setup possible; without buying a real TETRA radio and risking interferance. I wanted to say thank you for writing this. Maybe once I learn C and Python I'll try updating this project and dependencies to work on modern Debian versions as a way of saying thanks.

**Comment by sq5bpf** [comment]
Thanks, i'm happy that you like this software. 

I've seen what you did in your fork, and that probably does the job (didn't test it,  but it looks ok). 

That said, the "resume" functionality should work differently. Upon loss of signal telive should remember information about adjacent cells in the same network, try to find the strongest one, and use it's information to find other frequencies. After all, if you're riding the train, and you're listening to the train network, you don't want to suddenly start listening to the electricity company :)

And if that "smart resume" doesn't work, then it should fallback to normal scanning like you've implemented.

As you've probably noticed, I'm not actively maintaining this software, but i will put this on my todo list.
